### PR TITLE
Do not overwrite existing :SudoWrite

### PR DESCRIPTION
**Pull request by blueyed**
This might be provided by https://github.com/chrisbra/SudoEdit.vim
already.

### CODE REVIEW

**Comment by tpope** [comment]
Why is Eunuch supposed to yield? Because the plugin doesn't have "Sudo" in the name?

**Comment by blueyed** [comment]
SudoEdit is a specialized plugin for this purpose, providing more features and supports more edge cases.

**Comment by tpope** [comment]
Kind of ironic that Eunuch is the one to integrate with `sudoedit` (`sudo -e`), eh?

**Comment by blueyed** [comment]
Yes.

However, `$SUDO_COMMAND` is not set for me with `sudo -e foo`.  (it seems that Eunuch expects it to be `sudoedit`).  But I might be missing something, also did some quick grepping after your remark.

**Comment by tpope** [comment]
Well that's unfortunate but I was referring to the way it leverages `sudo -e` rather than calling `tee` directly, thus properly respecting `sudoedit` permissions.

**Comment by tpope** [comment]
I mean I guess I'll merge but based on the edge cases I'm aware of, mine still wins (:

**Comment by chrisbra** [comment]
I am not sure I fully understand what you are trying to say here. But I consider it a feature that SudoEdit is not called by `sudo -e`

**Comment by tpope** [comment]
No, the opposite. Eunuch's `:SudoEdit` calls out to `sudo -e`, so that if you grant file edit privileges in `/etc/sudoers`, it respects that. SudoEdit.vim instead requires you to grant privileges on `tee`, just based on some implementation detail that shouldn't concern the user.

**Pull request closed without merging**
